[window]
opacity = 0.9
blur = true
decorations = "None"
decorations_theme_variant = "Dark"
padding = { x = 10, y = 20 }

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size = 11.0
offset = { x = 1, y = 1 }

[colors.primary]
background = "#2E3440"
foreground = "#D8DEE9"

[colors.normal]
black   = "#3B4252"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#81A1C1"
magenta = "#B48EAD"
cyan    = "#88C0D0"
white   = "#E5E9F0"

[colors.bright]
black   = "#4C566A"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#81A1C1"
magenta = "#B48EAD"
cyan    = "#8FBCBB"
white   = "#ECEFF4"

[mouse]
hide_when_typing = true

[terminal]
osc52 = "CopyPaste"

[cursor]
style = "Beam"


[scrolling]
history = 10000
multiplier = 3

